CREATE SCHEMA IF NOT EXISTS COMPANY;
SET SEARCH_PATH TO COMPANY;
CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    FIRST_NAME VARCHAR(15) NOT NULL,
    LAST_NAME VARCHAR(15) NOT NULL,
    SSN CHAR(9) NOT NULL,
    BIRTHDATE DATE,
    ADDRESS VARCHAR(50),
    SEX CHAR,
    SALARY DECIMAL(10, 2),
    SUPERSSN CHAR(9),
    DEPT_NUM INT NOT NULL,
    CONSTRAINT EMPPK PRIMARY KEY (SSN)
);

CREATE TABLE IF NOT EXISTS DEPARTMENT
(
    DEPT_NAME VARCHAR(15) NOT NULL,
    DEPT_NUM INT NOT NULL,
    MANAGER_SSN CHAR(9) NOT NULL,
    MANAGER_START_DATE DATE,
    DEPT_OVERHEAD INT NOT NULL,
    CONSTRAINT DEPTPK PRIMARY KEY (DEPT_NUM),
    CONSTRAINT DEPTUDNAME UNIQUE (DEPT_NAME)
);

CREATE TABLE IF NOT EXISTS DEPT_LOCATIONS
(
    DEPT_NUM INT NOT NULL,
    DEPT_LOCATION VARCHAR(15) NOT NULL,
    CONSTRAINT DEPTLOCPK PRIMARY KEY (DEPT_NUM, DEPT_LOCATION),
    FOREIGN KEY (DEPT_NUM) REFERENCES DEPARTMENT (DEPT_NUM)
);

CREATE TABLE IF NOT EXISTS PROJECT
(
    PROJECT_NAME VARCHAR(15) NOT NULL,
    PROJECT_NUM INT,
    PROJECT_LOCATION VARCHAR(15),
    DEPT_NUM INT NOT NULL,
    PRIMARY KEY (PROJECT_NUM),
    CONSTRAINT PROJECTUPNAME UNIQUE (PROJECT_NAME),
    CONSTRAINT PROJECTFKDNUM
    FOREIGN KEY (DEPT_NUM) REFERENCES DEPARTMENT (DEPT_NUM)
);

CREATE TABLE IF NOT EXISTS WORKS_ON
(
    ESSN CHAR(9) NOT NULL,
    PROJECT_NUM INT NOT NULL,
    HOURS DECIMAL(3, 1),
    PRIMARY KEY (ESSN, PROJECT_NUM),
    FOREIGN KEY (ESSN) REFERENCES EMPLOYEE (SSN),
    CONSTRAINT WORKSONFKPNO FOREIGN KEY (PROJECT_NUM)
    REFERENCES PROJECT (PROJECT_NUM)
);

CREATE TABLE IF NOT EXISTS DEPENDENT
(
    ESSN CHAR(9) NOT NULL,
    DEPENDENT_NAME VARCHAR(15) NOT NULL,
    SEX CHAR,
    BIRTHDATE DATE,
    RELATIONSHIP VARCHAR(15),
    PRIMARY KEY (ESSN, DEPENDENT_NAME),
    CONSTRAINT DEPFKESSN FOREIGN KEY (ESSN) REFERENCES EMPLOYEE (SSN)
);



COPY EMPLOYEE (
    FIRST_NAME,
    LAST_NAME,
    SSN,
    BIRTHDATE,
    ADDRESS,
    SEX,
    SALARY,
    SUPERSSN,
    DEPT_NUM
) FROM '/usr/local/pg/employee.csv' DELIMITER ';' HEADER;


COPY department
  (
  DEPT_NAME,
  DEPT_NUM,
  MANAGER_START_DATE,
  MANAGER_SSN
  )
FROM '/usr/local/pg/department.csv' DELIMITER ';' HEADER;

COPY projects
  (
  PROJECT_NAME,
  PROJECT_NUM,
  PROJECT_LOCATION,
  DEPT_NUM
  )
FROM '/usr/local/pg/projects.csv'
DELIMITER ';' HEADER;

COPY dept_locations 
  (
  DEPT_NUM, 
  DEPT_LOCATION
  )
FROM '/usr/local/pg/Dept_locations.csv'
DELIMITER ';' HEADER;

COPY works_on 
  (
  ESSN, 
  PROJECT_NUM, 
  NULLIF(HOURS, "")
  )
FROM '/usr/local/pg/works_on.csv'
DELIMITER ';' HEADER;

COPY dependent 
  (
  ESSN, 
  DEPENDENT_NAME, 
  SEX, 
  BIRTHDATE, 
  RELATIONSHIP
  )
FROM '/usr/local/pg/dependent.csv'
DELIMITER ';' HEADER;


/*
ALTER TABLE DEPARTMENT
ADD CONSTRAINT DEPTMGRFK FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPFKDNO FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPFKSUPERSSN
FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE(Ssn)
ON DELETE SET NULL ON UPDATE CASCADE ;
*/
