CREATE SCHEMA IF NOT EXISTS COMPANY;
SET SEARCH_PATH TO COMPANY;

-- Create Tables
-- Dep value 1000 means no dep is assigned
CREATE TABLE IF NOT EXISTS EMPLOYEE
( 
  FIRST_NAME VARCHAR(15) NOT NULL ,
  LAST_NAME VARCHAR(15) NOT NULL ,
  SSN CHAR(9) ,
  BIRTHDATE DATE,
  ADDRESS VARCHAR(30),
  SEX CHAR,
  SALARY DECIMAL(10,2), 
  SUPER_SSN CHAR(9),
  DEPT_NUM INT NOT NULL DEFAULT 1000,
  PRIMARY KEY (Ssn)
);

CREATE TABLE IF NOT EXISTS DEPARTMENT
( 
  DEPT_NAME VARCHAR(15) NOT NULL,
  DEPT_NUM INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  MANAGER_SSN CHAR(9) NOT NULL DEFAULT '888665555',
  MANAGER_START_DATE DATE,
  CONSTRAINT DEPTPK 
  PRIMARY KEY (DEPT_NUM) ,
  CONSTRAINT DEPTSK 
  UNIQUE (DEPT_NAME)
);

CREATE TABLE IF NOT EXISTS DEPT_LOCATIONS
( 
  DEPT_NUM INT NOT NULL,
  DEPT_LOCATION VARCHAR(15) NOT NULL,
  PRIMARY KEY (DEPT_NUM, DEPT_LOCATION),
  FOREIGN KEY (DEPT_NUM) REFERENCES DEPARTMENT(DEPT_NUM) 
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PROJECT
( 
  PROJECT_NAME VARCHAR(15) NOT NULL,
  PROJECT_NUM INT NOT NULL,
  PROJECT_LOCATION VARCHAR(15),
  DEPT_NUM INT NOT NULL,
  PRIMARY KEY (PROJECT_NUM, PROJECT_LOCATION),
  UNIQUE (PROJECT_NAME),
  UNIQUE (PROJECT_NUM),
  FOREIGN KEY (DEPT_NUM) REFERENCES DEPARTMENT(DEPT_NUM)
);

CREATE TABLE IF NOT EXISTS WORKS_ON
( 
  Essn CHAR(9) NOT NULL,
  Pno INT NOT NULL,
  Hours DECIMAL(3 ,1) NOT NULL,
  PRIMARY KEY (Essn , Pno),
  FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn),
  FOREIGN KEY (Pno) REFERENCES PROJECT(PROJECT_NUM) 
);

CREATE TABLE IF NOT EXISTS DEPENDENT
( 
  Essn CHAR(9) NOT NULL,
  Dependent_name VARCHAR(15) NOT NULL,
  Sex CHAR,
  Bdate DATE,
  Relationship VARCHAR(15),
  PRIMARY KEY (Essn , Dependent_name),
  FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn)
);

